require('core.setup-plugins')
require('core.mappings')
require('core.colors')
require('core.settings')

-- Plugins
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.telescope')
require('plugins.bufferline')
require('plugins.toggleterm')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-autotag')
require('plugins.cmp')
require('plugins.sneak')
require('plugins.comment')
