require("core.setup-plugins")
require("core.mappings")
require("core.colors")
require("core.settings")

-- Plugins
require("modules.lsp")
require("modules.nvim-tree")
require("modules.treesitter")
require("modules.telescope")
require("modules.bufferline")
require("modules.toggleterm")
require("modules.nvim-autopairs")
require("modules.nvim-ts-autotag")
require("modules.cmp")
require("modules.sneak")
require("modules.comment")
require("modules.which-key")
require("modules.mason")
require("modules.mason-lspconfig")
require("modules.mason-null-ls")
require("modules.lualine")
require("modules.null-ls")
require("modules.intelephense")
-- require("modules.ultisnips")
